### ISSUE TITLE
[FLAKY TEST] ErrorTests.Elastic.Apm.Tests.ErrorTests.ChangeTransactionContextAfterError

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1070]
ErrorTests.Elastic.Apm.Tests.ErrorTests.ChangeTransactionContextAfterError seems to be a flaky test:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-1055/4/tests

```
Error
System.NullReferenceException : Object reference not set to an instance of an object.
Stacktrace
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Elastic.Apm.Tests.ErrorTests.<>c__DisplayClass0_0.<ChangeTransactionContextAfterError>b__0(ITransaction t) in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1055/apm-agent-dotnet/test/Elastic.Apm.Tests/ErrorTests.cs:line 51
   at Elastic.Apm.Api.Tracer.CaptureTransaction(String name, String type, Action`1 action, DistributedTracingData distributedTracingData) in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1055/apm-agent-dotnet/src/Elastic.Apm/Api/Tracer.cs:line 80
   at Elastic.Apm.Tests.ErrorTests.ChangeTransactionContextAfterError() in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1055/apm-agent-dotnet/test/Elastic.Apm.Tests/ErrorTests.cs:line 27
```

**Comment by russcam** [comment]
This is addressed in #1106
