### ISSUE TITLE
[FLAKY TEST] LabelTests.Elastic.Apm.Tests.LabelTests.SingleLabelOnTransactionTestsDec(number: "457")

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1071]
LabelTests.Elastic.Apm.Tests.LabelTests.SingleLabelOnTransactionTestsDec(number: "457") seems to be a flaky test:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-1065/2/tests

```
Error
Expected jsonString "{"duration":0.655,"id":"fbfd9af093df7244","sampled":false,"name":"test","outcome":"unknown","sample_rate":0.0,"span_count":{"dropped":0,"started":0},"timestamp":1606782712212747,"trace_id":"1b5cfb885dc0c74b88224baaf5025c67","type":"test"}" to contain ""tags":{"myLabel":457.0}".
Stacktrace
Expected jsonString "{"duration":0.655,"id":"fbfd9af093df7244","sampled":false,"name":"test","outcome":"unknown","sample_rate":0.0,"span_count":{"dropped":0,"started":0},"timestamp":1606782712212747,"trace_id":"1b5cfb885dc0c74b88224baaf5025c67","type":"test"}" to contain ""tags":{"myLabel":457.0}".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] becauseArgs)
   at Elastic.Apm.Tests.LabelTests.SingleLabelOnTransactionTests(Object labelValue) in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1065/apm-agent-dotnet/test/Elastic.Apm.Tests/LabelTests.cs:line 48
   at Elastic.Apm.Tests.LabelTests.SingleLabelOnTransactionTestsDec(String number) in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1065/apm-agent-dotnet/test/Elastic.Apm.Tests/LabelTests.cs:line 84
```

**Comment by russcam** [comment]
This is addressed in #1106
