### ISSUE TITLE
[FLAKY TEST] LoggerTests.Elastic.Apm.Tests.LoggerTests.PayloadSenderNoUserNamePwPrintedForServerUrlWithServerReturn

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1074]
`LoggerTests.Elastic.Apm.Tests.LoggerTests.PayloadSenderNoUserNamePwPrintedForServerUrlWithServerReturn` looks to be a flaky test:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-1062/5/tests

```
Error
Expected inMemoryLogger.Lines to contain 1 item(s), but found 0.
Stacktrace
Expected inMemoryLogger.Lines to contain 1 item(s), but found 0.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.HaveCount(Int32 expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 53
   at Elastic.Apm.Tests.LoggerTests.PayloadSenderNoUserNamePwPrintedForServerUrlWithServerReturn() in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1062/apm-agent-dotnet/test/Elastic.Apm.Tests/LoggerTests.cs:line 375
```

**Comment by russcam** [comment]
This now seems to be addressed as part of #1101
