### ISSUE TITLE
v1.7.1 Newtonsoft 11.0.0.0 assembly not found

### ISSUE THREAD

**Issue by mdrgeniebelt** [elastic/apm-agent-dotnet#1117]
**Describe the bug**
Hi, so after upgrading to 1.7.1 I started having weird exceptions on application start. The weird thing is that I can't replicate it locally, happens only in docker container in cloud.

```
Exception 01 ===================================
Type: System.IO.FileNotFoundException
Source: Elastic.Apm.Report.Serialization.PayloadItemSerializer, Elastic.Apm, Version=1.7.1.0, Culture=neutral, PublicKeyToken=ae7400d2c189cf22
Message: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
Trace:    at Elastic.Apm.Report.Serialization.PayloadItemSerializer..ctor(IConfigurationReader configurationReader)
   at Elastic.Apm.Report.PayloadSenderV2..ctor(IApmLogger logger, IConfigSnapshot config, Service service, System system, IApmServerInfo apmServerInfo, HttpMessageHandler httpMessageHandler, String dbgName, Boolean isEnabled)
   at Elastic.Apm.AgentComponents..ctor(IApmLogger logger, IConfigurationReader configurationReader, IPayloadSender payloadSender, IMetricsCollector metricsCollector, ICurrentExecutionSegmentsContainer currentExecutionSegmentsContainer, ICentralConfigFetcher centralConfigFetcher, IApmServerInfo apmServerInfo)
   at Elastic.Apm.AgentComponents..ctor(IApmLogger logger, IConfigurationReader configurationReader, IPayloadSender payloadSender)
   at Elastic.Apm.AspNetCore.ApmMiddlewareExtension.UseElasticApm(IApplicationBuilder builder, IConfiguration configuration, IDiagnosticsSubscriber[] subscribers)
   at Elastic.Apm.NetCoreAll.ApmMiddlewareExtension.UseAllElasticApm(IApplicationBuilder builder, IConfiguration configuration)
   at Organisation.Infrastructure.FrameworkExtensions.UseElasticApmMetricsConfigured(IApplicationBuilder app, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /app/src/Organisation/Infrastructure/FrameworkExtensions.cs:line 93
   at Organisation.Startup.Configure(IApplicationBuilder app, ILogger`1 logger) in /app/src/Organisation/Startup.cs:line 108
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Location: 
Method: Void .ctor(Elastic.Apm.Config.IConfigurationReader) (0, 0)
```

That's how we configure the client:

```
public static IApplicationBuilder UseElasticApmMetricsConfigured(this IApplicationBuilder app, IConfiguration configuration, IWebHostEnvironment webHostEnvironment)
{
    if (webHostEnvironment.IsLocal())
    {
         return app;
    }

    app.UseAllElasticApm(configuration);
    
    return app;
}
```

Any ideas what might be wrong? Thanks in advance.

**Comment by mdrgeniebelt** [comment]
Further investigation: it happens only when I upgrade 

- https://www.nuget.org/packages/coverlet.collector package from 1.3.0 to 3.0.0 

But these package has no dependencies so it seems to me like....magic 🧙‍♂️

**Comment by russcam** [comment]
On the surface, this seems like an issue with coverlet.collector. It doesn't have declared nuget package dependencies, but it does ship all of its dependencies in the package, which includes Newtonsoft.Json 9.0.0.0

![image](https://user-images.githubusercontent.com/208231/104261406-317b6300-54d1-11eb-839a-cad83dbd49bc.png)

I wouldn't expect this to affect running the application though, as these are all in the `build` directory of the package, so are used by MSBuild at compile time.

The application build logs might shed more light on what is happening here. Can you [collect the logs as a structured binary log](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/Binary-Log.md) and use [Structured Log Viewer](https://msbuildlog.com/) to investigate? Super silly question, but Newtonsoft.Json 11.0.0.0 is included in the files packaged in your docker container?

**Comment by mdrgeniebelt** [comment]
Closing this one as it was `coverlet` package causing this issue, nothing related to APM nuget :)
