### ISSUE TITLE
 {AwsCloudMetadataProvider} Unable to get aws cloud metadata

### ISSUE THREAD

**Issue by e-jlion** [elastic/apm-agent-dotnet#1283]
Hi：
  My microservice also encountered this warning log, but this caused the microservice health check to fail？？？

 {AwsCloudMetadataProvider} Unable to get aws cloud metadata

      System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 3 seconds elapsing.

       ---> System.TimeoutException: The operation was canceled.

       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         --- End of inner exception stack trace ---

         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

         at Elastic.Apm.Cloud.AwsCloudMetadataProvider.GetMetadataAsync()

info: Elastic.Apm[0]

      {GcpCloudMetadataProvider} Unable to get gcp cloud metadata

      System.Net.Http.HttpRequestException: Name or service not known (metadata.google.internal:80)

       ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

         at Elastic.Apm.Cloud.GcpCloudMetadataProvider.GetMetadataAsync()

info: Elastic.Apm[0]

      {AzureCloudMetadataProvider} Unable to get azure cloud metadata

      System.Net.Http.HttpRequestException: No route to host (169.254.169.254:80)

       ---> System.Net.Sockets.SocketException (113): No route to host

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)

         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         --- End of inner exception stack trace ---

         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

         at Elastic.Apm.Cloud.AzureCloudMetadataProvider.GetMetadataAsync()

**Comment by russcam** [comment]
The agent tries to get cloud metadata from the cloud provider's metadata endpoint in order to send this data to APM server for use in the APM traces and UI. The default configuration value is set to `auto` which will try to get metadata by trying AWS, Azure and GCP metadata endpoints. If you're running in a specific cloud environment, [the `CloudProvider` configuration value can be set to that cloud provider](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-cloud-provider), and if you want to disable it completely, the value can be set to `none`.

> My microservice also encountered this warning log, but this caused the microservice health check to fail？？？

Are you able to explain a bit more how the warning logs caused the health checks to fail?

**Comment by gregkalapos** [comment]
These are [logs on Info level](https://github.com/elastic/apm-agent-dotnet/blob/c061236367df7b12a16e8e75d9d0abe12db34dfa/src/Elastic.Apm/Cloud/AwsCloudMetadataProvider.cs#L85). I remember we discussed that we purposely don't print this as warning or error, since if the application is not running in a specific cloud, then it's expected that the detection won't work.

One thing we could maybe consider is to reword the log a little bit adding something like "The monitored process likely does not run in {Provider}, in which case it's expected to not being able to detect metadata for {Provider}" (or something similar).
