### ISSUE TITLE
[BUG] CI - Test failure in Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests

### ISSUE THREAD

**Issue by adam-stokes** [elastic/apm-agent-dotnet#1360]
### APM Agent version
The version of the `Elastic.Apm` nuget package used

NuGet.CommandLine v5.8.0

This is testing the master branch:

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/master/563/pipeline

### Environment

**Operating system and version:**

Windows 2019

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :

- dotnet-sdk-3.1.100-win-x64
- dotnet-sdk-5.0.100-win-x64

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):

.NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001)

### Describe the bug

Error in test:

```
[
  {
    "age": 1,
    "duration": 60.099,
    "errorDetails": "Expected object to be Error, but found Trace.",
    "errorStackTrace": "Expected object to be Error, but found Trace.\nStack Trace:\n   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)\n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)\n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)\n   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)\n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)\n   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)\n   at Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable() in C:\\Users\\jenkins\\workspace\\tnet_apm-agent-dotnet-mbp_master\\apm-agent-dotnet\\test\\Elastic.Apm.Tests\\BackendCommTests\\CentralConfig\\CentralConfigFetcherTests.cs:line 72\nStandard Output:\n    Elastic APM .NET Tests> 381> Xunit> [2021-07-26 00:53:21.056 +00:00][Info] - {LoggingTestBase} Starting test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable...\n    Elastic APM .NET Tests> 381> Xunit> [2021-07-26 00:54:21.155 +00:00][Info] - {LoggingTestBase} Finished test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable",
    "id": "io.jenkins.blueocean.service.embedded.rest.junit.BlueJUnitTestResult:Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests%3Ajunit%2FElastic.Apm.Tests.BackendCommTests.CentralConfig%2FCentralConfigFetcherTests%2FInitializing___Parallel___Windows__NET_Core___Test___CentralConfigFetcherTests_Elastic_Apm_Tests_BackendCommTests_CentralConfig_CentralConfigFetcherTests_Should_Update_Logger_That_Is_ILogLevelSwitchable",
    "name": "Initializing / Parallel / Windows .NET Core / Test / CentralConfigFetcherTests.Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable – Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests",
    "status": "FAILED"
  }
]
```

Non json:
```
 Expected object to be Error, but found Trace.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable() in C:\Users\jenkins\workspace\tnet_apm-agent-dotnet-mbp_master\apm-agent-dotnet\test\Elastic.Apm.Tests\BackendCommTests\CentralConfig\CentralConfigFetcherTests.cs:line 72
Standard Output:
    Elastic APM .NET Tests> 381> Xunit> [2021-07-26 00:53:21.056 +00:00][Info] - {LoggingTestBase} Starting test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable...
    Elastic APM .NET Tests> 381> Xunit> [2021-07-26 00:54:21.155 +00:00][Info] - {LoggingTestBase} Finished test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable 
 ```

**Comment by gregkalapos** [comment]
2 tests have this issue on `CentralConfigFetcherTests.Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests`:

- `Should_Update_Logger_That_Is_ILogLevelSwitchable`
- `Should_Update_IgnoreMessageQueues_Configuration`

Both deactivated for now.

**Comment by gregkalapos** [comment]
Closing for now.
