### ISSUE TITLE
[CI] Master branch failing

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-dotnet#1369]
A [new failure has been detected](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/master/566/) on the master branch with the test: `Initializing / Parallel / Linux / Test / Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.CentralConfigFetcherTests.Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable (from Elastic.Apm.Tests.dll.Elastic.Apm.Tests.dll) `

The error seems to relate to the logging level that's been set:

```
Error Message

Expected testLogger.LogLevelSwitch.Level to be Error, but found Trace.

Stacktrace

Expected testLogger.LogLevelSwitch.Level to be Error, but found Trace.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable() in /var/lib/jenkins/workspace/tnet_apm-agent-dotnet-mbp_master/apm-agent-dotnet/test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs:line 78
Standard Output:
    Elastic APM .NET Tests> 332> Xunit> [2021-08-04 07:08:48.064 +00:00][Info] - {LoggingTestBase} Starting test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable...
    Elastic APM .NET Tests> 332> Xunit> [2021-08-04 07:09:48.202 +00:00][Info] - {LoggingTestBase} Finished test: Elastic.Apm.Tests.BackendCommTests.CentralConfig.CentralConfigFetcherTests.Should_Update_Logger_That_Is_ILogLevelSwitchable
```

Could somebody please investigate this failure? Thanks!

**Comment by gregkalapos** [comment]
There is already an issue for it: https://github.com/elastic/apm-agent-dotnet/issues/1360 also with a PR where I tried to fix, with no success so far.

I close this as a duplicate - we are already working on this.

**Comment by cachedout** [comment]
My fault. I searched the repo but didn't see it. Thanks, @gregkalapos
