### ISSUE TITLE
MissingMethodException on net48 with Elastic.Apm.Extensions.Hosting

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1579]
Reported [via discuss](https://discuss.elastic.co/t/elastic-apm-extensions-hosting-doesnt-work-with-net48-if-you-already-have-a-dependency-on-microsoft-extensions-dependencyinjection-version-5-0/289403) - see more details there.

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.Hosting.IHostingEnvironment Microsoft.Extensions.Hosting.HostBuilderContext.get_HostingEnvironment()'.
   at Elastic.Apm.Extensions.Hosting.HostBuilderExtensions.<>c__DisplayClass0_1.<UseElasticApm>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Elastic.Apm.Extensions.Hosting.HostBuilderExtensions.<>c.<UseElasticApm>b__0_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
```

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseElasticApm(new HttpDiagnosticsSubscriber());
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm.Extensions.Hosting" Version="1.12.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
  </ItemGroup>

</Project>
```

**Comment by z1c0** [comment]
So, this is one of those "dependency hell problems". Here are my findings:

In the provided [gist](https://gist.github.com/ismaelhamed/fcc18ba7ffed9c31cddaa4cc98aefdda) we have the situation, where the application ...
* ... targets `net48`, which implements `netstandard20` (see [.NET matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)).
* ... references `Microsoft.Extensions.Hosting` in version `5.0.0`
  * This introduces a transitive dependency to `Microsoft.Extensions.Hosting.Abstractions.dll` in version `5.0.0`.
* ... also references `Elastic.Apm.Extensions.Hosting` 
  * which also has a transitive dependency to `Microsoft.Extensions.Hosting` but in version `2.1.0` for `netstandard20` (see [project file](https://github.com/elastic/apm-agent-dotnet/blob/3f31afa9e91e8adc2d7e57bfca83333f54725aed/src/Elastic.Apm.Extensions.Hosting/Elastic.Apm.Extensions.Hosting.csproj#L23)).

Unfortunately, there has been a **breaking change** between those versions in the `HostBuilderContext` class when it comes to the `HostingEnvironment` property.

* Version `5.0.0`:
`public IHostEnvironment HostingEnvironment { get; set; }`

* Version `2.1.0`:
`public IHostingEnvironment HostingEnvironment { get; set; }`

So we have `IHostEnvironment` vs `IHostingEnvironment` ⚠️
(Note that the `IHostingEnvironment` interface has been [deprecated](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.ihostingenvironment?view=aspnetcore-6.0)).

This results in the reported problem:
* At compile time we have `IHostingEnvironment`
* At runtime we suddenly find `IHostEnvironment` which results in the `MissingMethodException`.

Possible solutions that I'd like to discuss @gregkalapos:
* Upgrade the dependencies in the agent projects to a more recent version (>= `5.0.0`) which should be possible since these are still `netstandard20`. But there might be side affects or compatiblity concerns that I'm not aware of yet.
* Access the `HostingEnvironment` property via reflection which prevents the runtime exception.
