### ISSUE TITLE
[BUG] Exception thrown while trying to stop transaction System.NullReferenceException

### ISSUE THREAD

**Issue by vnovichek** [elastic/apm-agent-dotnet#1736]
### APM Agent version
1.16.0.0

### Environment

**Operating system and version:**
Linux Centos 7

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
NET Core 2.1

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
netcoreapp2.1

### Describe the bug
```
trce: Elastic.Apm[0]
{HttpDiagnosticListenerCoreImpl} Called with key: `System.Net.Http.Request'
trce: Elastic.Apm[0]
{HttpDiagnosticListenerCoreImpl} Unrecognized key `System.Net.Http.Request'
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[11]
Copying bytes 0-8402/8403 of file /static/media/message.57d1f3e8.mp3 to the response body
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[11]
Copying bytes 0-15507/15508 of file /static/media/NotificationSound.9326244d.mp3 to the response body
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
Connection id "0HMIFF8QNR50K" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
Connection id "0HMIFF8QNR50K" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
Connection id "0HMIFF8QNR50K" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
Connection id "0HMIFF8QNR50L" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
Connection id "0HMIFF8QNR50L" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
Connection id "0HMIFF8QNR50L" sending FIN.
fail: Elastic.Apm[0]
{ApmMiddleware} Exception thrown while trying to stop transaction
System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.AspNetCore.WebRequestTransactionCreator.StopTransaction(Transaction transaction, HttpContext context, IApmLogger logger)
fail: Elastic.Apm[0]
{ApmMiddleware} Exception thrown while trying to stop transaction
System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.AspNetCore.WebRequestTransactionCreator.StopTransaction(Transaction transaction, HttpContext context, IApmLogger logger)
2022-06-16 04:29:50.0806 [usavc-kiosk2:5] [ERROR] [Elastic.Apm] {ApmMiddleware} Exception thrown while trying to stop transaction System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.AspNetCore.WebRequestTransactionCreator.StopTransaction(Transaction transaction, HttpContext context, IApmLogger logger)
2022-06-16 04:29:50.0806 [usavc-kiosk2:71] [ERROR] [Elastic.Apm] {ApmMiddleware} Exception thrown while trying to stop transaction System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.AspNetCore.WebRequestTransactionCreator.StopTransaction(Transaction transaction, HttpContext context, IApmLogger logger)
trce: Elastic.Apm[0]
{Transaction} Ended Transaction{Id: 818a780df3a7fb4a, TraceId: 498439fd09d00342aa5e799b5ff69642, ParentId: null, Name: GET /static/media/NotificationSound.9326244d.mp3, Type: request, Outcome: Success, IsSampled: True}. Start time: 2022-06-16 09:29:50.0255630 UTC (as timestamp: 1655371790025563), End time: 2022-06-16 09:29:50.0812440 UTC (as timestamp: 1655371790081244), Duration: 55.681ms
trce: Elastic.Apm[0]
{Transaction} Ended Transaction{Id: 0881e4dc035ab74a, TraceId: 361f1beccba32645972f89f77e0d7c36, ParentId: null, Name: GET /static/media/message .57d1f3e8.mp3, Type: request, Outcome: Success, IsSampled: True}. Start time: 2022-06-16 09:29:50.0266370 UTC (as timestamp: 1655371790026637), End time: 2022-06-16 09:29:50.0815660 UTC (as timestamp: 1655371790081566), Duration: 54.929ms
2022-06-16 04:29:50.0816 [usavc-kiosk2:5] [DEBUG] [Elastic.Apm] {PayloadSenderV2} Enqueued Transaction. newEventQueueCount: 3. MaxQueueEventCount: 1000. Transaction: Transaction{Id: 818a780df3a7fb4a, TraceId: 498439fd09d00342aa5e799b5ff69642, ParentId: null, Name: GET /static/media/NotificationSound.9326244d.mp3, Type: request, Outcome: Success, IsSampled: True}.
dbug: Elastic.Apm[0]
{PayloadSenderV2} Enqueued Transaction. newEventQueueCount: 3. MaxQueueEventCount: 1000. Transaction: Transaction{Id: 818a780df3a7fb4a, TraceId: 498439fd09d00342aa5e799b5ff69642, ParentId: null, Name: GET /static/media/NotificationSound.9326244d.mp3, Type: request, Outcome: Success, IsSampled: True}.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 57.3934ms 206 audio/mpeg
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
Connection id "0HMIFF8QNR50K" stopped.
dbug: Elastic.Apm[0]
dbug: Elastic.Apm[0]
{PayloadSenderV2} Enqueued Transaction. newEventQueueCount: 4. MaxQueueEventCount: 1000. Transaction: Transaction{Id: 0881e4dc035ab74a, TraceId: 361f1beccba32645972f89f77e0d7c36, ParentId: null, Name: GET /static/media/message.57d1f3e8.mp3, Type: request, Outcome: Success, IsSampled: True}.
2022-06-16 04:29:50.0816 [usavc-kiosk2:71] [DEBUG] [Elastic.Apm] {PayloadSenderV2} Enqueued Transaction. newEventQueueCount: 4. MaxQueueEventCount: 1000. Transaction: Transaction{Id: 0881e4dc035ab74a, TraceId: 361f1beccba32645972f89f77e0d7c36, ParentId: null, Name: GET /static/media/message.57d1f3e8.mp3, Type: request, Outcome: Success, IsSampled: True}.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 56.8349ms 206 audio/mpeg
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
Connection id "0HMIFF8QNR50L" stopped.
```

**Comment by gregkalapos** [comment]
This was fixed in https://github.com/elastic/apm-agent-dotnet/pull/1729 which was released in [v1.16.1](https://github.com/elastic/apm-agent-dotnet/releases/tag/v1.16.1) (it's also released on NuGet).

Could you please just update?

I'm closing this, because to me this seems like an already fixed issue with an existing patch. If it turns out to be something else, and v1.16.1 doesn't fix it, feel free to reopen.
