### ISSUE TITLE
[BUG] APM agent not working on .NET 7

### ISSUE THREAD

**Issue by christallire** [elastic/apm-agent-dotnet#1900]
### APM Agent version
The version of the `Elastic.Apm` nuget package used
https://github.com/elastic/apm-agent-dotnet/releases/download/v1.16.0/ElasticApmAgent_1.16.0.zip

### Environment

**Operating system and version:**
Ubuntu focal arm64v8

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.NET 7

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net7.0

### Describe the bug
```
# kubectl logs -f backoffice-657d64b495-n849r app
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at StartupHook.InvokerLoaderMethod(Assembly loaderAssembly) in C:\Users\jenkins\workspace\net_apm-agent-dotnet-mbp_PR-1727\apm-agent-dotnet\src\ElasticApmAgentStartupHook\StartupHook.cs:line 179
   at StartupHook.Initialize() in C:\Users\jenkins\workspace\net_apm-agent-dotnet-mbp_PR-1727\apm-agent-dotnet\src\ElasticApmAgentStartupHook\StartupHook.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
```
### To Reproduce

1. Create a docker container with `ENV DOTNET_STARTUP_HOOKS=/app/ElasticApmAgentStartupHook.dll`
2. Run
3. Profit

#### Expected behavior
Container should run

#### Actual behavior
Container failed to run at start up

**Comment by z1c0** [comment]
Hi @christallire,
thanks for reporting this issue.
We will be looking into it at our earliest convenience and make sure .NET 7.0 is fully supported.

**Comment by z1c0** [comment]
Hi again @christallire,
we are still working on .NET 7 support (see also #1903) and it should be included in the next release.
The release that contains .NET 7 support should also resolve this issue.
Thanks for your patience.

**Comment by z1c0** [comment]
Hi @christallire,
the issue has been fixed and will be included in the upcoming release of the APM agent.
Thanks again for reaching out!
