### ISSUE TITLE
Investigate/Fix flaky unit test: Elasticsearch_Span_Does_Not_Have_Http_Child_Span

### ISSUE THREAD

**Issue by z1c0** [elastic/apm-agent-dotnet#1998]
This test randomly (but regularly) fails in CI builds:

`Initializing / Parallel / Linux / Test / ElasticsearchTests.Elastic.Apm.Elasticsearch.Tests.ElasticsearchTests.Elasticsearch_Span_Does_Not_Have_Http_Child_Span – Elastic.Apm.Elasticsearch.Tests.ElasticsearchTests`

Details:

```
 Docker.DotNet.DockerApiException : Docker API responded with status code=Conflict, response={"message":"Container 368603faac811b5a59fa9bcfd2fb8fcd3bca314eb3888d030874aa74ad83a598 is not running"}

Stack Trace:
   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ExecOperations.ExecCreateContainerAsync(String id, ContainerExecCreateParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct)
   at DotNet.Testcontainers.Configurations.UntilUnixCommandIsCompleted.Until(ITestcontainersContainer testcontainers, ILogger logger)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.<>c__DisplayClass41_1.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass1_0.<<WaitUntil>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntil(Func`1 wait, Int32 frequency, Int32 timeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Start(String id, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at Elastic.Apm.Elasticsearch.Tests.ElasticsearchFixture.InitializeAsync() in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1970/apm-agent-dotnet/test/Elastic.Apm.Elasticsearch.Tests/ElasticsearchFixture.cs:line 31 
```

**Comment by stevejgordon** [comment]
Closing as unplanned.
