### ISSUE TITLE
[BUG] Unable to cast object of type 'Elastic.Apm.Model.NoopSpan' to type 'Elastic.Apm.Model.Span'

### ISSUE THREAD

**Issue by molszews** [elastic/apm-agent-dotnet#2176]
### APM Agent version
1.23.0

### Environment
net6.0

### Describe the bug
Error messages are logged when apm is disabled.

### To Reproduce
Start app with `UseAllElasticApm()` and "Enabled" setting set to false in `appsettings.json`
```
  "ElasticApm": {
    "Enabled": false
}
```
after while error messages starts to log

```
[14:10:53 ERR] {AuditDiagnosticsListener} An exception occured calling OnNext on an ElasticsearchDiagnostic observer
System.InvalidCastException: Unable to cast object of type 'Elastic.Apm.Model.NoopSpan' to type 'Elastic.Apm.Model.Span'.
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.TryStartElasticsearchSpan(String name, Span& span, Uri instanceUri)
   at Elastic.Apm.Elasticsearch.AuditDiagnosticsListener.OnAudit(String event, Audit audit)
   at Elastic.Apm.Elasticsearch.AuditDiagnosticsListener.<.ctor>b__0_0(KeyValuePair`2 a)
   at Elasticsearch.Net.Diagnostics.TypedDiagnosticObserverBase`1.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.HandleOnNext(KeyValuePair`2 kv)
[14:10:53 ERR] {AuditDiagnosticsListener} An exception occured calling OnNext on an ElasticsearchDiagnostic observer
System.InvalidCastException: Unable to cast object of type 'Elastic.Apm.Model.NoopSpan' to type 'Elastic.Apm.Model.Span'.
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.TryStartElasticsearchSpan(String name, Span& span, Uri instanceUri)
   at Elastic.Apm.Elasticsearch.AuditDiagnosticsListener.OnAudit(String event, Audit audit)
   at Elastic.Apm.Elasticsearch.AuditDiagnosticsListener.<.ctor>b__0_0(KeyValuePair`2 a)
   at Elasticsearch.Net.Diagnostics.TypedDiagnosticObserverBase`1.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.HandleOnNext(KeyValuePair`2 kv)
[14:10:53 ERR] {HttpConnectionDiagnosticsListener} An exception occured calling OnNext on an ElasticsearchDiagnostic observer
System.InvalidCastException: Unable to cast object of type 'Elastic.Apm.Model.NoopSpan' to type 'Elastic.Apm.Model.Span'.
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.TryStartElasticsearchSpan(String name, Span& span, Uri instanceUri)
   at Elastic.Apm.Elasticsearch.HttpConnectionDiagnosticsListener.OnRequestData(String event, RequestData requestData)
   at Elastic.Apm.Elasticsearch.HttpConnectionDiagnosticsListener.<.ctor>b__0_0(KeyValuePair`2 a)
   at Elasticsearch.Net.Diagnostics.TypedDiagnosticObserverBase`2.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.HandleOnNext(KeyValuePair`2 kv)
[14:10:53 ERR] {HttpConnectionDiagnosticsListener} Failed to find current span in ConcurrentDictionary 00-372ff7fc0a235ce546f5c9a0e39ec8e9-91b96ddd006263d9-00
[14:10:53 ERR] {HttpConnectionDiagnosticsListener} An exception occured calling OnNext on an ElasticsearchDiagnostic observer
System.InvalidCastException: Unable to cast object of type 'Elastic.Apm.Model.NoopSpan' to type 'Elastic.Apm.Model.Span'.
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.TryStartElasticsearchSpan(String name, Span& span, Uri instanceUri)
   at Elastic.Apm.Elasticsearch.HttpConnectionDiagnosticsListener.OnRequestData(String event, RequestData requestData)
   at Elastic.Apm.Elasticsearch.HttpConnectionDiagnosticsListener.<.ctor>b__0_0(KeyValuePair`2 a)
   at Elasticsearch.Net.Diagnostics.TypedDiagnosticObserverBase`2.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at Elastic.Apm.Elasticsearch.ElasticsearchDiagnosticsListenerBase.HandleOnNext(KeyValuePair`2 kv)

```

#### Expected behavior
No errors re casting `NoopSpan` to `Span` are logged.
No errors re `Failed to find current span in ConcurrentDictionary 00-372ff7fc0a235ce546f5c9a0e39ec8e9-91b96ddd006263d9-00` are logged.

**Comment by JeremyBessonElastic** [comment]
Sorry for this really late reply.

We are advising to use the latest version.

Despite all my effort, I haven't manage to replicate the issue with some more recent versions. I suspect that it should be fine now. 

Please, if the problem still exists, creates another issue with information on the error happens.
