### ISSUE TITLE
[BUG] Version mismatch between Elastic.Apm.SqlClient and other Elastic.Apm.* components throws an exception

### ISSUE THREAD

**Issue by gsm1be** [elastic/apm-agent-dotnet#2284]
### APM Agent version
The version of the `Elastic.Apm` nuget package used: **_1.25.3_** (or anything above 1.24.*)

### Environment

**Operating system and version:** Microsoft Windows 10.0.19045

**.NET Framework/Core name and version** (e.g. .NET 4.6.2, NET Core 3.1.100) : .NET 8 (.NET 8.0.1)

**Application Target Framework(s)** (e.g. net462, netcoreapp3.1): net8.0

### Describe the bug
The currently available versions of the nuget packages are: 
```xml
    <PackageReference Include="Elastic.Apm.AspNetCore" Version="1.25.3" />
    <PackageReference Include="Elastic.Apm.EntityFrameworkCore" Version="1.25.3" />
    <PackageReference Include="Elastic.Apm.SqlClient" Version="1.23.0" />
```
When having this mismatch of versions, the application craches with an unhandled exception:
```c#
INFO: TLS termination is disabled
INFO: starting process
Unhandled exception. System.MethodAccessException: Attempt by method 'Elastic.Apm.SqlClient.SqlClientDiagnosticSubscriber.Subscribe(Elastic.Apm.IApmAgent)' to access method 'Elastic.Apm.CompositeDisposable..ctor()' failed.
   at Elastic.Apm.SqlClient.SqlClientDiagnosticSubscriber.Subscribe(IApmAgent agentComponents)
   at Elastic.Apm.ApmAgentExtensions.Subscribe(IApmAgent agent, IDiagnosticsSubscriber] subscribers)
   at Elastic.Apm.AspNetCore.ApplicationBuilderExtensions.UseElasticApm(IApplicationBuilder builder, ApmAgent agent, IApmLogger logger, IDiagnosticsSubscriber] subscribers)
   at Elastic.Apm.AspNetCore.ApplicationBuilderExtensions.UseElasticApm(IApplicationBuilder builder, IConfiguration configuration, IDiagnosticsSubscriber] subscribers)
   at Program.<Main>$(String] args) in /vsts/agent/si0vmc4268-2/1158/s/src/service/Service/Program.cs:line 118
```

### To Reproduce

1. Use the versions mentioned above in a .net web app, and set up the APM agents:
```c#
app.UseElasticApm(builder.Configuration,
  new HttpDiagnosticsSubscriber(),  /* Enable tracing of outgoing HTTP requests */
  new SqlClientDiagnosticSubscriber(), /* Enable tracing of Sql Queries*/
  new EfCoreDiagnosticsSubscriber() /* Enable tracing of database calls through EF Core*/
);
```
2. Then start the app

#### Expected behavior
Application should start normally and the agents should be able to subscribe to diagnostics.

#### Actual behavior
See above.

**Comment by stevejgordon** [comment]
Hi, @gsm1be.

Apologies for the slow response to your issue.

Since 1.23 we no longer ship the SQL instrumentation in the separate `Elastic.Apm.SqlClient` package and its available with `Elastic.Apm`. You should be able to remove the package reference to `Elastic.Apm.SqlClient` and this runtime exception should go away.

**Comment by gsm1be** [comment]
Thank you @stevejgordon for the info and the support! Removing the reference and changing the using works.

**Comment by stevejgordon** [comment]
Great news, thanks @gsm1be.
