### ISSUE TITLE
Nullreference in AWS Lambda

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#491]
Callstack:

```
[Error] Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction: Unknown error responding to request: NullReferenceException:
System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.AspNetCore.ApmMiddleware.GetHttpVersion(String protocolString)
at Elastic.Apm.AspNetCore.ApmMiddleware.FillSampledTransactionContextRequest(HttpContext context, Transaction transaction)
at Elastic.Apm.AspNetCore.ApmMiddleware.InvokeAsync(HttpContext context)
at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.ProcessRequest(ILambdaContext lambdaContext, Context context, InvokeFeatures features, Boolean rethrowUnhandledError)
```

Based on the stack I'd say this happens when we read the HTTP version.

Based on the callstack this happens [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L265) and i suspect we pass `null` into that method [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L164) to get the HTTP version. Maybe `context.Request.Protocol` is `null`.

Given that HTTP version is optional we can have a quick fix for this. It'd be also worth reproducing it and see why we can't get this info.

**Comment by gregkalapos** [comment]
The nullref is fixed in #512  - I tested it and there is no crash anymore, the application works as expected. 

Unfortunately I discovered another problem during my testing - I opened #518. Closing this now, since the nullref problem is solved and the other problem is either not related to AWS and can also happen somewhere else, or it's something AWS related but that'd mean that offering AWS Lambda support will take more effort than expected.
