### ISSUE TITLE
Failing ConvenientApiTransactionTests.AsyncTask

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#797]
Error Message
```
Expected value to be greater or equal to 1.0, but found 0.981.
```

Stacktrace

```
Expected value to be greater or equal to 1.0, but found 0.981.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`1.BeGreaterOrEqualTo(T expected, String because, Object[] becauseArgs)
   at Elastic.Apm.Tests.ShouldWaitDurationExtensions.BeGreaterOrEqualToMinimumSleepLength(NullableNumericAssertions`1 duration) in C:\Users\jenkins\workspace\tnet_apm-agent-dotnet-mbp_master\apm-agent-dotnet\test\Elastic.Apm.Tests\Extensions\ShouldWaitDurationExtensions.cs:line 11
   at Elastic.Apm.Tests.ApiTests.ConvenientApiTransactionTests.<AssertWith1TransactionAsync>d__29.MoveNext() in C:\Users\jenkins\workspace\tnet_apm-agent-dotnet-mbp_master\apm-agent-dotnet\test\Elastic.Apm.Tests\ApiTests\ConvenientApiTransactionTests.cs:line 658
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Elastic.Apm.Tests.ApiTests.ConvenientApiTransactionTests.<AsyncTask>d__11.MoveNext() in C:\Users\jenkins\workspace\tnet_apm-agent-dotnet-mbp_master\apm-agent-dotnet\test\Elastic.Apm.Tests\ApiTests\ConvenientApiTransactionTests.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Fails on Windows .NET Framework

**Comment by gregkalapos** [comment]
Added more logging in #798. 

So far I was unable to repro in CI - so merging the additional logging, once it fails again we'll have more logs and I'll pick this up again.

**Comment by gregkalapos** [comment]
Will re-open once we have more logs.
